version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
skip_tags: true
environment:
  SONAR_SCANNER_OPTS: -Xmx2048m
  SonarKey:
    secure: 2mQfOEBZCqM3BI8UAAc2wkRkvrTNsWKwRyFiKgk4Khfpl/SUrJSxcGnmB+CJB7OZ
  SonarGithubKey:
    secure: SY6rvHCSxikpJpkcDR/JsnMDc41rD9+L2w0pr370Qd1cUZJJJY4rxVISzdmTf1fG
  SonarOrg: jscoobyced-github
  SonarUrl: https://sonarcloud.io
  SonarProjectKey: sawan
  ClientApp: ClientApp
  MsBuildScanner: C:\ProgramData\chocolatey\lib\sonarscanner-msbuild-netcoreapp2.0\tools
  SonarExclusions: coverage/**/*,**/*.xml,**/*.spec.t*,**/Program.cs,**/Startup.cs,**/node_modules/**/*,**/wwwroot/dist/**/*,*.cshtml
  SonarCoverageExclusions: "**/*.js,**/tests/*"
  SonarScanner: sonar-scanner-3.2.0.1227\bin
  LcovInfo: coverage\lcov.info
  TsConfig: tsconfig.json
  CsTarget: test sawan-tests\sawan-tests.csproj
  CsFilter: +[sawan*]* -[sawan*]*Program -[sawan*]*Startup +[tests*]*
  CsCoverage: coverage.xml
  TsCoverage: coverage\coverage-final.json
  TsReportPath: test-report.xml
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - choco install --no-progress sonarscanner-msbuild-netcoreapp2.0
  - choco install --no-progress codecov
build_script:
  - ps: >-
      & .\scripts\build\build.ps1
test_script:
  - ps: >-
      & .\scripts\build\run_tests.ps1
after_test:
  - ps: >-
      & .\scripts\build\after_test.ps1
artifacts:
  - path: publish
    type: Zip
  - path: src\coverage.xml
notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
deploy:
  tag: $(appveyor_build_version)
  release: sawan.io-v$(appveyor_build_version)
  description: 'https://sawan.io website. Latest release is the latest version.'
  provider: GitHub
  auth_token:
    secure: WiUWgpamFs7jnPR5HzUbh1UN3tELVb8fMQR8cXgilTDUe5JjF2voK6b880x1wQiI
  draft: false
  prerelease: false
  on:
    branch: master
